server {
    listen 80;
    server_name testchart.khumar.pro;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 127.0.0.1:8445 ssl;
    http2 on;
    server_name testchart.khumar.pro;

    ssl_certificate /etc/letsencrypt/live/testchart.khumar.pro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/testchart.khumar.pro/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TestChartTLS:10m;

    root /var/www/testchart/current;
    index index.html;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options DENY always;

    location = /index.html {
        expires -1;
        try_files $uri =404;
    }

    location /assets/ {
        expires 1y;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
